### ISSUE TITLE
Full example

### ISSUE THREAD

**Issue by nick-wellinghoff-sp** [softsimon/angular-2-dropdown-multiselect#14]
Can you post a project where you list this component as a dependency and use it in the project? I followed the instructions and it seems like a lot of stuff is missing to allow npm etc to index things right. I can't use the module without specifying the full relative path to your ts file. Once I do get it running I get a lot of errors. A example project that uses your component would be awesome!

**Comment by ordinaryzelig** [comment]
I also think a full example would be very useful. I fanagled my way to finally get it to work, but I get the feeling it was intended to be as easy as it sounds in the README. These are the steps I had to take to get it to work (Using angular-cli with angular 2.0.0-beta.17):

1.  Install as local npm package.
1. Add to my component file: `import { IMultiSelectOption, IMultiSelectSettings, IMultiSelectTexts } from '../../node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown';`. (I am new to npm, so I don't know how the importing works, but an import path directly to the file was the only way I could get it to find the files.)
1. in `node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts`, add `export` in front of `class MultiSelectSearchFilter` so it can be imported in my module file in next step.
1. Add to my module file: `import { MultiselectDropdown, MultiSelectSearchFilter } from '../../node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown';` Note the README says `MultiselectDropdownModule`, but I think it's a typo and should be `MultiselectDropdown` ([PR](https://github.com/softsimon/angular-2-dropdown-multiselect/issues/14)).
1. Add `MultiselectDropdown` and `MultiSelectSearchFilter` to @NgModule declarations.

After copy/pasting examples into my template, it worked.

Again, I'm new to angular2, so please correct these observations if they are wrong:

- The import path is somehow not recognized.
- The `searchFilter` pipe needed to be manually imported to be used.

**Comment by nick-wellinghoff-sp** [comment]
Yeah I did the same thing to get it working. It looks like the package author has not included the right index files etc so npm can load the ts using the shorthand notation. So I had to put the full paths to everything as well.

**Comment by softsimon** [comment]
Should be fixed now. Readme has been updated.

**Comment by dluk** [comment]
Spent more than an hour trying to get this up and running, there is something really wrong with this the package. As far as I know importing the module should be enough, but it still doesn't recognise the component <ss-multiselect-dropdown>

**Comment by nicholasguyett** [comment]
@dluk your issue might be related to #19.  Currently, the npm package does not include the compiled JS files.  So if you are not referencing the TS file directly, none of your imports will be able to pick it up, as there is no JS file to import.

Currently the workaround is to manually run the typescript compiler from within the package directory.  I've already setup the tsconfig.json file for compilation, so all you should have to do is run the command by itself.

Once #19 is complete, the workaround will no longer be necessary.

**Comment by saviorgp** [comment]
I am having a similar issue. I downloaded the latest version and followed the install steps according to the README file. Both .ts and .map files are there, i used npm to install it. However, when i try to run my app i get the following:

Can't bind to 'options' since it isn't a known property of 'ss-multiselect-dropdown'.
1. If 'ss-multiselect-dropdown' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ss-multiselect-dropdown' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("                            </button -->
                                  <ss-multiselect-dropdown [ERROR ->][options]="myOptions" [(ngModel)]="selectedOptions" (ngModelChange)="onChange($event)"></ss-multisele"): e@40:59
'ss-multiselect-dropdown' is not a known element:
1. If 'ss-multiselect-dropdown' is an Angular component, then verify that it is part of this module.
2. If 'ss-multiselect-dropdown' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. 

This is the very 1st time i am using Angular 2. Can you guys help ?

**Comment by nicholasguyett** [comment]
@saviorgp, did you include `MultiselectDropdownModule` in the imports array in your module?  The error message sounds like you didn't import it.  It must be imported into the module your template is being rendered in.

**Comment by saviorgp** [comment]
Hi Nicholas, thanks for the quick answer! Yes, i did. I followed every step described on the installation guide.  What might  i be missing ?

**Comment by guerson** [comment]
I think you forgot To include it in the System Config

```
System.config({
  map: {
    
    'app': './src',
    ...
    'angular-2-dropdown-multiselect': 'npm:angular-2-dropdown-multiselect/src/multiselect-dropdown.js',
    ...
  },
  //packages defines our app package
  packages: {
    ...
  }
});
```

**Comment by Rosscotini** [comment]
Also facing the same issue. A full example would be amazing to see how its really done

**Comment by arlamaeen** [comment]
@Rosscotini did you manage to solve the issue?

**Comment by gustavolira** [comment]
Same problem here. 
I followed all the steps exactly like at full-example

**Comment by rafkos83** [comment]
Anyone had the same issue? I've added everything  like the example stated and still this does not work. Any ideas what can be the problem?
